### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by winkbrace**
## Description

Add documentation for the helper functions

## Motivation and context

I'd like to use this package in my projects, but I don't want all my colleagues to have to search through the source to find what functions are available.

## How has this been tested?

n/a

Although I added the `test` script to composer, so that it matches the documentation. ;)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked.

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] If my change requires a change to the documentation, I have updated it accordingly.
- [x] My code follows the code style of this project.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by sebastiaanluca** [comment]
Awesome, thank you for this! It's still a dev package, but since you mention you want to use it in your projects, do you want me to release a first (draft) version? I'm thinking of upping the required version to PHP 7.1 and renaming that one method to `is_active_route` too.

**Comment by winkbrace** [comment]
Glad you like it :) A release would be welcome, yeah.

I agree that `is_active_route` would be better. The required version of php 7.1 would be too soon for our production environment that is still on php 7.0.

**Comment by sebastiaanluca** [comment]
@winkbrace Pushed a 0.1.0 draft version so updates to develop don't break existing code + completed the readme (without details) :) Let me know if there should be any problems!

**Comment by winkbrace** [comment]
Great, thanks! :)


;} Bas de Ruiter

2017-01-10 0:24 GMT+01:00 Sebastiaan Luca <notifications@github.com>:

**Pull request merged**
