### PR TITLE
Fix hardcoded $$ reference

### PR DESCRIPTION
**Pull request by danielsdeboer**
## PR Type

What kind of pull request is this? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Extend feature (non-breaking change which extends existing functionality)
- [ ] Change feature (non-breaking change which either changes or refactors existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## What does it change?

Removed a hardcoded reference to '$$' in `Pipe\Item`.

## Why this PR?

If I want to change the identifier it didn't work as expected.

## How has this been tested?

Full test stack passes.

## Checklist

To facilitate merging your change and the approval of this PR, please make sure you've reviewed and applied the following:

- This PR addresses exactly one issue
- All changes were made in a fork of this project (preferably also in a separate branch)
- It follows the code style of this project
- Tests were added to cover the changes
- All previously existing tests still pass
- If the change to the code requires a change to the documentation, it has been updated accordingly

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by sebastiaanluca** [comment]
Hi, thanks for the PR!

Good catch, just one question: how are you changing the identifier? Did you extend the class to gain access to the identifier? And how are you using the class; global method `take()` helper or `new Item`? Maybe a `setIdentifier` would be of more use then.

**Comment by danielsdeboer** [comment]
I had one instance where I wanted to change the ID, I extended the class
with a constructor that took an optional second `$placeholder` argument.
I'm not super sure a setter would be useful, I feel like doing
`take('something')->setIdentifier('##')->pipe(...etc)` would be
inconvenient enough that no one would do it.

**Comment by sebastiaanluca** [comment]
Yeah, an instance setter might not be that useful. Perhaps a static setter or a second parameter like you did? Just thinking out loud since I'm adding a ton more helpers and maybe I can add this too in the next version.

```
// Static setter, then used for all pipe operator items. Could be set in a service provider if you're using Laravel like the Migration class does.
Item::setIdentifier('??');

// Optional instance constructor parameter
new Item('value', '??');
```

**Comment by sebastiaanluca** [comment]
Merged!

**Comment by danielsdeboer** [comment]
Personally I think an optional constructor parameter is the most useful. 

What would actually be super interesting is if the `Item` class used a magic `__call()` to delegate method calls to `pipe()`. Then you could do this:

```
take('item')
    ->strtoupper()
    ->get()
```

It's completely optional, users can still call `pipe()` if they wish. But it does decrease the friction of using piping if you don't have to call `pipe()` plus the callable as a string.

This would do it:

```
public function __call ($name, $args)
{
    return $this->pipe($name, ...$args);
}
```

**Comment by sebastiaanluca** [comment]
Oooh, I like that idea! Consider it implemented in the next release 😊

**Pull request closed without merging**
